[paths]
train  = "data/raw/train/train.csv"
gas  = "data/raw/gas/gas_prices.csv"
electricity  = "data/raw/electricity/electricity_prices.csv"
clients  = "data/raw/clients/client.csv"
weather_station_map  = "data/raw/weather_station_to_county_mapping.csv"
weather_forecast  = "data/raw/weather_forecast/forecast_weather.csv"
historical_weather  = "data/raw/historical_weather/historical_weather.csv"

[preprocessing]
offset_hours = 11
lag_days = 7
