[info]
key = "energy-producer"
name = "energy-producer"
topic = "energy_topic"
frequency = 1.0
input_data_path = "data/predict-energy-behavior-of-prosumers/electricity_prices.csv"

[producer]
bootstrap_servers = "broker:9092"
acks = 0
api_version = [3, 4, 0]