[info]
key = "weather-producer"
name = "weather-producer"
topic = "weather_topic"
frequency = 1.0
input_data_path = "data/predict-energy-behavior-of-prosumers/historical_weather.csv"

[producer]
bootstrap_servers = "broker:9092"
acks = 0
api_version = [3, 4, 0]