[info]
name = "weather-forecast-producer"
topic = "weather_forecast_topic"
frequency = 1.0
input_data_path = "data/predict-energy-behavior-of-prosumers/forecast_weather.csv"

[producer]
bootstrap_servers = "broker:9092"
acks = 0
api_version = [3, 4, 0]